apiVersion: v1
kind: Service
metadata:
  name: gestion-academica
spec:
  selector:
    app: gestion-academica
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer  # O NodePort si no tienes LoadBalancer
