apiVersion: v1
kind: Service
metadata:
  name: gestion-academica
  namespace: webapp
spec:
  type: Loadbalancer 
  selector:
    app: gestion-academica
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000