apiVersion: v1
kind: Pod
metadata:
  name: nginx-dev1
  namespace: test
  labels:
    app: nginx-dev
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "devweb-app"
    vault.hashicorp.com/agent-inject-secret-credentials.env: "secret/data/devwebapp/config"
    vault.hashicorp.com/agent-inject-template-credentials.env: |
      {{- with secret "secret/data/devwebapp/config" -}}
      POSTGRES_USER={{ .Data.data.username }}
      POSTGRES_PASSWORD={{ .Data.data.password }}
      {{- end }}
spec:
  serviceAccountName: internal-app
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "==> Iniciando NGINX con variables desde Vault"
          cat /vault/secrets/credentials.env
          env $(cat /vault/secrets/credentials.env) nginx -g "daemon off;"
