apiVersion: v1
kind: Pod
metadata:
  name: busybox-vault
  namespace: vault
  labels:
    app: busybox-vault
  annotations:
    vault.hashicorp.com/agent-inject: "true"
    vault.hashicorp.com/role: "devweb-app"
    vault.hashicorp.com/agent-inject-secret-credentials.env: "secret/data/devwebapp/config"
    vault.hashicorp.com/agent-inject-template-credentials.env: |
      {{- with secret "secret/data/devwebapp/config" -}}
      POSTGRES_USER={{ .Data.data.username }}
      POSTGRES_PASSWORD={{ .Data.data.password }}
      {{- end }}
spec:
  serviceAccountName: internal-app
  containers:
    - name: busybox
      image: busybox
      command: ["/bin/sh", "-c"]
      args:
        - |
          echo "==> Mostrando variables inyectadas desde Vault:"
          cat /vault/secrets/credentials.env
          echo "==> Ejecutando sleep para mantener el pod activo"
          sleep 3600