apiVersion: apps/v1
kind: Deployment
metadata:
  name: alpine-vault
  namespace: test2
  labels:
    app: alpine-vault
spec:
  replicas: 3
  selector:
    matchLabels:
      app: alpine-vault
  template:
    metadata:
      labels:
        app: alpine-vault
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "devweb-app"
        vault.hashicorp.com/agent-inject-secret-credentials.env: "secret/data/devwebapp/config"
        vault.hashicorp.com/agent-inject-template-credentials.env: |
          {{- with secret "secret/data/devwebapp/config" -}}
          POSTGRES_USER={{ .Data.data.username }}
          POSTGRES_PASSWORD={{ .Data.data.password }}
          {{- end }}
    spec:
      serviceAccountName: internal-app
      containers:
        - name: alpine
          image: alpine:latest
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "==> Mostrando variables inyectadas desde Vault:"
              cat /vault/secrets/credentials.env
              env $(cat /vault/secrets/credentials.env) sleep 3600
