apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp-deployment
  labels:
    app: miapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miapp
  template:
    metadata:
      labels:
        app: miapp
    spec:
      containers:
      - name: miapp
        image: antoneletn/miapp2025:v1  # <-- Cambia si usas otro nombre o registry privado
        ports:
        - containerPort: 3000