apiVersion: apps/v1
kind: Deployment
metadata:
  name: miapp2025-deployment
  labels:
    app: miapp2025
spec:
  replicas: 1  # Número de réplicas (pods)
  selector:
    matchLabels:
      app: miapp2025
  template:
    metadata:
      labels:
        app: miapp2025
    spec:
      containers:
      - name: miapp2025-container
        image: antoneletn/miapp2025:v1  # Imagen de Docker Hub
        ports:
        - containerPort: 3000