apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: postgres-vault
  namespace: default
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.vault.svc:8200"
    roleName: "demo"
    objects: |
      - objectName: "username"
        secretPath: "secret/postgres"
        secretKey: "username"
      - objectName: "password"
        secretPath: "secret/postgres"
        secretKey: "password"
  secretObjects:
    - secretName: vault-db-creds
      type: Opaque
      data:
        - objectName: username
          key: username
        - objectName: password
          key: password
