imagen_backend: putic.work.gd/pasantias2025/backend-yatic@sha256:29376ccd546a5de94969ea5b2c913d5f483f10c2e20cd24e5b86822f81493377
#imagen_backend: nginx:alpine
imagen_frontend: httpd:latest
imagen_portal: busybox:latest
imagen_reporteador: alpine:latest

vaultAnnotations:
  vault.hashicorp.com/agent-inject: 'true'
  vault.hashicorp.com/role: 'yatic-test-role'
  vault.hashicorp.com/agent-inject-secret-env_vars.sh: 'secret/data/backend/env'
  vault.hashicorp.com/agent-inject-template-env_vars.sh: |
    {{- with secret "secret/data/backend/env" -}}
    {{- range $k, $v := .Data.data }}
    export {{ $k }}="{{ $v }}"
    echo {{ $k }}="{{ $v }}" >> /app/.env
    {{- end }}
    {{- end }}

imagePullSecret: ""
